#!/bin/bash

# Usage:
# echo -e "${RED}red text${NC} normal text"
# printf "${RED}red text${NC} normal text\n"

readonly BLACK="\033[0;30m"
readonly DARK_GRAY="\033[1;30m"
readonly RED="\033[0;31m"
readonly LIGHT_RED="\033[1;31m"
readonly GREEN="\033[0;32m"
readonly LIGHT_GREEN="\033[1;32m"
readonly ORANGE="\033[0;33m"
readonly YELLOW="\033[1;33m"
readonly BLUE="\033[0;34m"
readonly LIGHT_BLUE="\033[1;34m"
readonly PURPLE="\033[0;35m"
readonly LIGHT_PURPLE="\033[1;35m"
readonly CYAN="\033[0;36m"
readonly LIGHT_CYAN="\033[1;36m"
readonly LIGHT_GRAY="\033[0;37m"
readonly WHITE="\033[1;37m"
readonly NC="\033[0m" # No color